### ISSUE TITLE
[Meta]: Project Outstanding Items

### ISSUE THREAD

**Issue by devfreddy** [newrelic/nr1-workload-geoops#36]
# Geo Ops Workloads Outstanding Items

### Feat
- [x] NRQL, both input and rendering on the map
- [x] Marker hovers/clicks and side panels (Daniel, Freddy)
- [x] Display detailpanel when table row is clicked
- [x] Feat(View Map): Filter by Region. Keep in mind potential future need of Country/Municipality
- [x] Pass status of each MapLocation down to the MapMarker. Pull calculateStatus out of <MapLocationTable> into <ViewMap>, figure out status, change MapLocation data
- [x] [Favorites](https://github.com/newrelic/nr1-workload-geoops/issues/6)
- [x] Highlight visually the active marker

### Fix
- [x] favorite sorting is broken (sometimes)
- [x] limit description height in popover
- [x] navigate to empty state after deleting all maps
- [x] Navigation state changes between file upload and main nerdlet
- [x] Retrieve Incidents for Entities (Freddy)
- [x] styling on map location data page (Daniel)
- [x] flashes, are we allowed to do this (a side panel) without `<Modal>` ?
- [x] https://github.com/newrelic/nr1-workload-geoops/issues/37
- [ ] Styling: 
  - [x] Style type-ahead
  - [x] Style upload file nerdlet
  - [x] Style account picker
  - [ ] Remove ability to navigate through getting started steps if you haven't finished the step before
- [x] remove "submit" button, just utilize continue button
- [x] clicking on "continue" should take you to View Map

### Backlog
- [ ] Research: can we utilize a `<Dropdown label="My Account 1">` based <AccountPicker> from the platform team inside a form
- [ ] Identify components for nr1-community
- [ ] Feat: Ability to choose chart component for side panel for a map location (Backlog/Future)
- [ ] testing file upload schema failures (Backlog)
- [ ] Expand a timeline item by default depending on which was clicked in the detail panel. (Dependant on newrelic/nr1-community#55)
- [ ] Feat: Edit Map and Edit Map Location screens (Backlog)

> The "label" prop is deprecated. If you are using <Dropdown> as a form component, use <Select> instead (due 12/31/2020). 
> The new <AccountPicker> is based on Dropdown.
